#we will use the existing functions to convert
import sys, os
import numpy as np

sSystem_paths = os.environ['PATH'].split(os.pathsep)
sys.path.extend(sSystem_paths)
from pyes.system import define_global_variables
from pyes.system.define_global_variables import *

from pyes.toolbox.reader.text_reader_string import text_reader_string

sPath_pypest_python = sWorkspace_code +  slash + 'python' + slash + 'pypest' + slash + 'pypest_python'
sys.path.append(sPath_pypest_python)
from pypest.models.maces.inputs.pest import pest
from pypest.models.maces.inputs.pest_read_configuration_file import pest_read_configuration_file


from pypest.models.maces.inputs.xmlchange import xmlchange

def maces_convert_parameter_to_input_files(oPest_in):
    sWorkspace_simulation_relative = oPest_in.sWorkspace_simulation
    sCase = oPest_in.sCase
    sWorkspace_simulation = sWorkspace_scratch +  slash  + sWorkspace_simulation_relative
    sWorkspace_simulation_case  = sWorkspace_simulation + slash + sCase
    #there will be two steps,
    #first, we need to read the parameter file generated by pest
    #read hydro parameter
    sFilename_parameter = sWorkspace_simulation_case + slash + oPest_in.sFilename_hydro_parameter
    if os.path.isfile(sFilename_parameter):
        pass
    else:
        print('The file does not exist!')
        return
    aData_all = text_reader_string(sFilename_parameter, cDelimiter_in =',')
    aDummy = aData_all[0,:]
    nParameter = len(aDummy) - 1
    aParameter_list = aDummy[1: nParameter+1]

    ngrid = 1 
    aParameter_value = (aData_all[1:ngrid,1: nParameter+1]).astype(float)
    aParameter_value = np.asarray(aParameter_value)
    
    #second we will call the existing python function to convert

    #construct the command string

    #./xmlchange.py -f optpar_minac.xml -g M12MOD -p rhoSed -v 2650.0

    #for p in range(0, nParameter):
    sFilename  = sWorkspace_simulation_case + slash + 'optpar_minac.xml'
    sValue =  "{:16.2f}".format( aParameter_value[0] )
    #sCommand = '-f' + sFilename + ' -g M12MOD -p rhoSed -v '  + sValue
    xmlchange(filename=sFilename, group='M12MOD', parameter='Cz0',value=sValue)
    print('Finished')


    
    return
if __name__ == '__main__':
    sFilename_pest_configuration = '/qfs/people/liao313/03configuration/pypest/maces/pest.xml'
    aParameter  = pest_read_configuration_file(sFilename_pest_configuration)
    print(aParameter)    
    oPest = pest(aParameter)
    maces_convert_parameter_to_input_files(oPest)